test 3.11b3 builds in CI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -24,28 +24,32 @@ jobs:
     strategy:
       matrix:
         include:
-        - spec: cp27-manylinux_x86_64
-          cibw_version: cibuildwheel<2.0  # py2.7 is not supported on CIBW 2.0+
-          manylinux_img: manylinux1  # build really old Pythons on manylinux1
-        - spec: cp36-manylinux_x86_64
-          manylinux_img: manylinux1  # build really old Pythons on manylinux1
-        - spec: cp37-manylinux_x86_64
-        - spec: cp38-manylinux_x86_64
-        - spec: cp39-manylinux_x86_64
-        - spec: cp310-manylinux_x86_64
-        - spec: cp27-manylinux_i686
-          cibw_version: cibuildwheel<2.0  # py2.7 is not supported on CIBW 2.0+
-          manylinux_img: manylinux1  # build really old Pythons on manylinux1
-        - spec: cp36-manylinux_i686
-          manylinux_img: manylinux1  # build really old Pythons on manylinux1
-        - spec: cp37-manylinux_i686
-        - spec: cp38-manylinux_i686
-        - spec: cp39-manylinux_i686
-        - spec: cp310-manylinux_i686
-        - spec: cp39-musllinux_x86_64
-        - spec: cp310-musllinux_x86_64
-        - spec: cp39-musllinux_i686
-        - spec: cp310-musllinux_i686
+#        - spec: cp27-manylinux_x86_64
+#          cibw_version: cibuildwheel<2.0  # py2.7 is not supported on CIBW 2.0+
+#          manylinux_img: manylinux1  # build really old Pythons on manylinux1
+#        - spec: cp36-manylinux_x86_64
+#          manylinux_img: manylinux1  # build really old Pythons on manylinux1
+#        - spec: cp37-manylinux_x86_64
+#        - spec: cp38-manylinux_x86_64
+#        - spec: cp39-manylinux_x86_64
+#        - spec: cp310-manylinux_x86_64
+        - spec: cp311-manylinux_x86_64
+#        - spec: cp27-manylinux_i686
+#          cibw_version: cibuildwheel<2.0  # py2.7 is not supported on CIBW 2.0+
+#          manylinux_img: manylinux1  # build really old Pythons on manylinux1
+#        - spec: cp36-manylinux_i686
+#          manylinux_img: manylinux1  # build really old Pythons on manylinux1
+#        - spec: cp37-manylinux_i686
+#        - spec: cp38-manylinux_i686
+#        - spec: cp39-manylinux_i686
+#        - spec: cp310-manylinux_i686
+        - spec: cp311-manylinux_i686
+#        - spec: cp39-musllinux_x86_64
+#        - spec: cp310-musllinux_x86_64
+        - spec: cp311-musllinux_x86_64
+#        - spec: cp39-musllinux_i686
+#        - spec: cp310-musllinux_i686
+        - spec: cp311-musllinux_i686
     steps:
     - name: clone repo
       uses: actions/checkout@v2
@@ -67,6 +71,7 @@ jobs:
         CIBW_ENVIRONMENT_PASS_LINUX: CFLAGS  # ensure that the build container can see our overridden build config
         CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_img || '' }}
         CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_img || '' }}
+        CIBW_PRERELEASE_PYTHONS: 'True'
         CIBW_TEST_REQUIRES: pytest
         CIBW_TEST_COMMAND: PYTHONUNBUFFERED=1 python -m pytest {project}
       run: |
@@ -91,27 +96,36 @@ jobs:
     strategy:
       matrix:
         include:
-        # build for x86_64 under the default hosted macOS 10.x x86_64 runner
-        - spec: cp27-macosx_x86_64
-          cibw_version: cibuildwheel<2.0  # py2.7 is not supported on CIBW 2.0+
-        - spec: cp36-macosx_x86_64
-        - spec: cp37-macosx_x86_64
-        - spec: cp38-macosx_x86_64
-        - spec: cp39-macosx_x86_64
-        - spec: cp310-macosx_x86_64
-        # build for arm64 under a hacked macOS 12 self-hosted x86_64-on-arm64 runner until arm64 is fully supported
-        # FIXME: ? cp38-macosx_arm64 requires special handling and fails some test_zdist tests under cibw 2.1.2, skip it (so Apple's XCode python3 won't have a wheel)
-        - spec: cp39-macosx_arm64
+#        # build for x86_64 under the default hosted macOS 10.x x86_64 runner
+#        - spec: cp27-macosx_x86_64
+#          cibw_version: cibuildwheel<2.0  # py2.7 is not supported on CIBW 2.0+
+#        - spec: cp36-macosx_x86_64
+#        - spec: cp37-macosx_x86_64
+#        - spec: cp38-macosx_x86_64
+#        - spec: cp39-macosx_x86_64
+#        - spec: cp310-macosx_x86_64
+        - spec: cp311-macosx_x86_64
+#        # build for arm64 under a hacked macOS 12 self-hosted x86_64-on-arm64 runner until arm64 is fully supported
+#        # FIXME: ? cp38-macosx_arm64 requires special handling and fails some test_zdist tests under cibw 2.1.2, skip it (so Apple's XCode python3 won't have a wheel)
+#        - spec: cp39-macosx_arm64
+#          deployment_target: '11.0'
+#          runs_on: [self-hosted, macOS]
+#          run_wrapper: arch -arm64 bash --noprofile --norc -eo pipefail {0}
+#          sdkroot: macosx11.3
+#
+#        - spec: cp310-macosx_arm64
+#          deployment_target: '11.0'
+#          runs_on: [self-hosted, macOS]
+#          run_wrapper: arch -arm64 bash --noprofile --norc -eo pipefail {0}
+#          sdkroot: macosx11.3
+
+        - spec: cp311-macosx_arm64
           deployment_target: '11.0'
           runs_on: [self-hosted, macOS]
           run_wrapper: arch -arm64 bash --noprofile --norc -eo pipefail {0}
           sdkroot: macosx11.3
 
-        - spec: cp310-macosx_arm64
-          deployment_target: '11.0'
-          runs_on: [self-hosted, macOS]
-          run_wrapper: arch -arm64 bash --noprofile --norc -eo pipefail {0}
-          sdkroot: macosx11.3
+
     steps:
     - name: clone repo
       uses: actions/checkout@v2
@@ -124,6 +138,7 @@ jobs:
     - name: build/test wheels
       env:
         CIBW_BUILD: ${{ matrix.spec }}
+        CIBW_PRERELEASE_PYTHONS: 'True'
         CIBW_TEST_REQUIRES: pytest
         CIBW_TEST_COMMAND: pip install pip --upgrade; cd {project}; PYTHONUNBUFFERED=1 pytest
       run: |
@@ -146,24 +161,26 @@ jobs:
         if-no-files-found: error
 
   windows:
-    runs-on: windows-2016
+    runs-on: windows-2019
     strategy:
       matrix:
         include:
-        - spec: cp27-win_amd64
-          cibw_version: cibuildwheel==1.10  # last release with proper py2.7 Windows support
-        - spec: cp36-win_amd64
-        - spec: cp37-win_amd64
-        - spec: cp38-win_amd64
-        - spec: cp39-win_amd64
-        - spec: cp310-win_amd64
-        - spec: cp27-win32
-          cibw_version: cibuildwheel==1.10  # last release with proper py2.7 Windows support
-        - spec: cp36-win32
-        - spec: cp37-win32
-        - spec: cp38-win32
-        - spec: cp39-win32
-        - spec: cp310-win32
+#        - spec: cp27-win_amd64
+#          cibw_version: cibuildwheel==1.10  # last release with proper py2.7 Windows support
+#        - spec: cp36-win_amd64
+#        - spec: cp37-win_amd64
+#        - spec: cp38-win_amd64
+#        - spec: cp39-win_amd64
+#        - spec: cp310-win_amd64
+        - spec: cp311-win_amd64
+#        - spec: cp27-win32
+#          cibw_version: cibuildwheel==1.10  # last release with proper py2.7 Windows support
+#        - spec: cp36-win32
+#        - spec: cp37-win32
+#        - spec: cp38-win32
+#        - spec: cp39-win32
+#        - spec: cp310-win32
+        - spec: cp311-win32
     steps:
     - name: clone repo
       uses: actions/checkout@v2
@@ -185,6 +202,7 @@ jobs:
     - name: build/test wheels
       env:
         CIBW_BUILD: ${{ matrix.spec }}
+        CIBW_PRERELEASE_PYTHONS: 'True'
       run: |
         python -m pip install --upgrade pip
         pip install "${{ matrix.cibw_version || 'cibuildwheel'}}"
